[project]
name = "eventon-scheduler"
version = "0.1.0"
description = "Optimization scheduler service built on OR-Tools"
requires-python = ">=3.11"
dependencies = [
  "ortools>=9.7.2996"
]

[project.optional-dependencies]
dev = [
  "black>=24.1.0",
  "ruff>=0.2.0"
]
